spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Infraction
    username: postgres
    password: astayoucode
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:Db/changelog.xml

server:
  port: 8082
